name: Hello world workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello: 
    runs-on: ubuntu-latest
    steps: 
      - name: hello world
      - uses: action/checkout@v2
        run: echo "Hello World 001"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
      - uses: action/checkout@v2
        runs: echo "Goodbye World 001"
        shell: bash

